import { marked } from 'marked';

const mathPlaceholders = new Map();
let mathCounter = 0;

function protectMath(text) {
    if (!text) return text;
    mathCounter = 0;
    mathPlaceholders.clear();

    return text.replace(/(\$\$[\s\S]*?\$\$|\$[\s\S]*?\$)/g, (match) => {
        const placeholder = `<!--MATH_PLACEHOLDER_${mathCounter}-->`;
        mathPlaceholders.set(placeholder, match);
        mathCounter++;
        return placeholder;
    });
}

function unprotectHtml(html) {
    if (!html || mathPlaceholders.size === 0) return html;
    let result = html;
    for (const [placeholder, original] of mathPlaceholders.entries()) {
        const regex = new RegExp(placeholder.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&'), 'g');
        result = result.replace(regex, original);
    }
    return result;
}

function escapeHtml(str) {
    if (!str || typeof str !== 'string') return '';
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

// Custom extension to handle [N] citations
const citationExtension = {
  name: 'citation',
  level: 'inline',
  start(src) { 
    if (typeof src !== 'string') return -1;
    return src.match(/\[\d+\]/)?.index; 
  },
  tokenizer(src, tokens) {
    const rule = /^\[(\d+)\]/;
    const match = rule.exec(src);
    if (match) {
      return {
        type: 'citation',
        raw: match[0],
        index: match[1]
      };
    }
  },
  renderer(token) {
    return `<button class="citation-btn text-blue-500 hover:underline font-mono text-xs align-super cursor-pointer select-none px-0.5 rounded hover:bg-blue-100 dark:hover:bg-blue-900/30 transition-colors" data-index="${token.index}">[${token.index}]</button>`;
  }
};

// Strict isolation: Escape raw HTML tags so they NEVER inject arbitrary DOM elements outside sandboxes
const safeHtmlRenderer = {
    html(token) {
        const raw = typeof token === 'string' ? token : (token.text || token.raw || '');
        if (!raw) return '';

        // Preserve math placeholders
        if (/^<!--MATH_PLACEHOLDER_\d+-->$/.test(raw.trim())) {
            return raw;
        }

        // Preserve status comments
        if (/^<!--\s*status:[a-zA-Z0-9_-]+\s*-->$/i.test(raw.trim())) {
            return raw;
        }

        // Allow inline-xml-tag codes generated by MessageContentRenderer
        if (/^<code\s+class=["']inline-xml-tag[^"']*["'][^>]*>[\s\S]*?<\/code>$/i.test(raw.trim())) {
            return raw;
        }

        // Allow safe inline text-level formatting tags without dangerous classes or styles
        if (/^<\/?(br|b|i|strong|em|code|kbd|del|s|strike|sub|sup)\b[^>]*>$/i.test(raw.trim())) {
            if (/\b(fixed|absolute|z-\d+|inset-|style=)\b/i.test(raw)) {
                return escapeHtml(raw);
            }
            return raw;
        }

        // Escape all other raw HTML tags (div, section, script, style, canvas, dialog, iframe, etc.)
        return escapeHtml(raw);
    }
};

marked.use({ 
    extensions: [citationExtension],
    renderer: safeHtmlRenderer
});

function wrapNakedCode(text) {
    if (!text) return text;
    
    // If text looks like HTML markup or has style/canvas but no markdown fences
    if ((text.includes('<!DOCTYPE') || text.includes('<html') || text.includes('<style>') || text.includes('<canvas')) && !text.includes('```')) {
        return "```html\n" + text + "\n```";
    }
    
    const codeStartRegex = /^(import\s|from\s|const\s|function\s|def\s|class\s)/;
    if (codeStartRegex.test(text.trim()) && !text.includes('```')) {
        return "```\n" + text + "\n```";
    }
    
    return text;
}

function normalizeTables(text) {
    if (!text || typeof text !== 'string') return text;
    const tableSeparatorRegex = /^(\|?\s*:?-+:?\s*\|?)+$/m;
    if (!tableSeparatorRegex.test(text)) return text;

    const lines = text.split('\n');
    const result = [];

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (typeof line === 'string' && /^(\|?\s*:?-+:?\s*\|?)+$/.test(line.trim())) {
            if (i > 0 && typeof lines[i-1] === 'string' && lines[i-1].includes('|')) {
                if (i > 1 && typeof lines[i-2] === 'string' && lines[i-2].trim() !== '' && !lines[i-2].includes('|')) {
                    result.splice(result.length - 1, 0, '');
                }
            }
        }
        result.push(line);
    }
    return result.join('\n');
}

function sanitizeDangerousTags(html) {
    if (!html) return html;

    // 1. Strip style, script, link blocks completely
    let clean = html.replace(/<style[\s\S]*?(?:<\/style>|$)/gi, '');
    clean = clean.replace(/<script[\s\S]*?(?:<\/script>|$)/gi, '');
    clean = clean.replace(/<link[^>]*?(?:>|$)/gi, '');

    // 2. Strip inline style attributes
    clean = clean.replace(/\sstyle\s*=\s*(?:"[^"]*"|'[^']*'|[^\s"'>]*)/gi, '');
    
    // 3. Neutralize inline event handlers
    clean = clean.replace(/\son\w+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s"'>]*)/gi, '');

    // 4. Neutralize dangerous URL schemes
    clean = clean.replace(/\s(href|src)\s*=\s*["']?\s*(?:javascript:|vbscript:|data:text\/html)[^"'>\s]*/gi, ' $1="#"');

    // 5. Security guard for iframes: Only allow verified YouTube embeds
    clean = clean.replace(/<iframe\b([^>]*)>/gi, (match, attrs) => {
        const srcMatch = attrs.match(/src=["']([^"']+)["']/i);
        if (srcMatch && /^https:\/\/(?:www\.)?(?:youtube\.com|youtube-nocookie\.com)\/embed\/(?:videoseries\?list=[a-zA-Z0-9_-]{12,64}|[a-zA-Z0-9_-]{11}(?:\?[a-zA-Z0-9_=&-]*)?)$/i.test(srcMatch[1])) {
            return `<iframe ${attrs} sandbox="allow-scripts allow-presentation" loading="lazy" referrerpolicy="strict-origin-when-cross-origin">`;
        }
        return '<!-- [Untrusted iframe embed removed] -->';
    });

    // 6. Strip any layout-escaping classes from remaining elements
    clean = clean.replace(/\sclass\s*=\s*["']([^"']*)["']/gi, (match, classList) => {
        const safeClasses = classList.split(/\s+/).filter(c => {
            return !/^(fixed|absolute|inset-0|inset-x-0|inset-y-0|w-screen|h-screen|z-\d+|z-\[\d+\]|backdrop-blur.*)$/i.test(c);
        }).join(' ');
        return safeClasses ? ` class="${safeClasses}"` : '';
    });

    return clean;
}

export function parsedMarkdown(content) {
    if (!content) return '';
    
    const trimmed = content.trim();
    if (trimmed.startsWith('graph ') || trimmed.startsWith('flowchart ') || trimmed.startsWith('sequenceDiagram') || trimmed.startsWith('classDiagram')) {
        if (!trimmed.startsWith('```')) {
            content = `\`\`\`mermaid\n${trimmed}\n\`\`\``;
        }
    }
  
    if (typeof content !== 'string') return '';
    
    const wrappedContent = wrapNakedCode(content);
    
    let normalizedContent = wrappedContent;
    try {
        normalizedContent = normalizeTables(wrappedContent);
    } catch (e) {
        console.warn("Markdown pre-processing (tables) failed:", e);
    }

    const protectedContent = protectMath(normalizedContent);
    
    const rawHtml = marked.parse(protectedContent, { 
        gfm: true, 
        breaks: true, 
        mangle: false, 
        headerIds: false,
        smartypants: false 
    });
    
    return sanitizeDangerousTags(unprotectHtml(rawHtml));
}

function tokenizeMarkdownPart(markdown) {
    if (!markdown.trim()) {
        return [{ type: 'space', raw: markdown }];
    }
    const protectedText = protectMath(markdown);
    const markedTokens = Array.from(marked.lexer(protectedText, { mangle: false, smartypants: false }));

    return markedTokens.map(token => {
        const unprotectedToken = { ...token };
        if (unprotectedToken.raw) {
            unprotectedToken.raw = unprotectHtml(unprotectedToken.raw);
        }
        if (unprotectedToken.text) { 
            unprotectedToken.text = unprotectHtml(unprotectedToken.text);
        }
        return unprotectedToken;
    });
}

function customTokenizer(text) {
    if (!text) return [];

    const codeBlockRegex = /(^\s*```[\s\S]*?^\s*```\s*?$)/gm;
    const parts = text.split(codeBlockRegex);

    const tokens = [];

    for (let i = 0; i < parts.length; i++) {
        const part = parts[i];
        if (!part) continue;

        if (i % 2 === 1) {
            const codeBlockMatch = part.match(/^\s*```(\w*)\r?\n([\s\S]*?)\r?\n?^\s*```\s*?$/m);
            if (codeBlockMatch) {
                tokens.push({
                    type: 'code',
                    lang: codeBlockMatch[1] || 'plaintext',
                    text: codeBlockMatch[2],
                    raw: part
                });
            } else {
                tokens.push(...tokenizeMarkdownPart(part));
            }
        } else {
            tokens.push(...tokenizeMarkdownPart(part));
        }
    }
    return tokens;
}

export function getContentTokensWithMathProtection(text) {
    return customTokenizer(text);
}